import { App } from 'vue'
import {
  Anchor,
  Affix,
  Alert,
  Avatar,
  AutoComplete,
  Button,
  Badge,
  BackTop,
  Breadcrumb,
  Collapse,
  Comment,
  Col,
  Card,
  Checkbox,
  Carousel,
  Cascader,
  Calendar,
  ConfigProvider,
  Descriptions,
  Dropdown,
  Divider,
  Drawer,
  DatePicker,
  Empty,
  Form,
  Input,
  Icon,
  Image,
  InputNumber,
  Layout,
  List,
  LocaleProvider,
  Mentions,
  Menu,
  Modal,
  Pagination,
  Progress,
  Popover,
  PageHeader,
  Popconfirm,
  Radio,
  Rate,
  Row,
  Result,
  Steps,
  Space,
  Select,
  Switch,
  Statistic,
  Slider,
  Spin,
  Skeleton,
  Tag,
  Table,
  Tooltip,
  Tree,
  Tabs,
  Timeline,
  Transfer,
  Typography,
  TimePicker,
  TreeSelect,
  Upload
} from 'ant-design-vue'

export default function setupUI(app: App) {
  app.use(Anchor)
  app.use(Affix)
  app.use(Alert)
  app.use(Avatar)
  app.use(AutoComplete)
  app.use(Button)
  app.use(Badge)
  app.use(BackTop)
  app.use(Breadcrumb)
  app.use(Collapse)
  app.use(Comment)
  app.use(Col)
  app.use(Card)
  app.use(Checkbox)
  app.use(Carousel)
  app.use(Cascader)
  app.use(Calendar)
  app.use(ConfigProvider)
  app.use(Descriptions)
  app.use(Dropdown)
  app.use(Divider)
  app.use(Drawer)
  app.use(DatePicker)
  app.use(Empty)
  app.use(Form)
  app.use(Input)
  app.use(Icon)
  app.use(Image)
  app.use(InputNumber)
  app.use(Layout)
  app.use(List)
  app.use(LocaleProvider)
  app.use(Mentions)
  app.use(Menu)
  app.use(Modal)
  app.use(Pagination)
  app.use(Progress)
  app.use(Popover)
  app.use(PageHeader)
  app.use(Popconfirm)
  app.use(Radio)
  app.use(Rate)
  app.use(Row)
  app.use(Result)
  app.use(Steps)
  app.use(Space)
  app.use(Select)
  app.use(Switch)
  app.use(Statistic)
  app.use(Slider)
  app.use(Spin)
  app.use(Skeleton)
  app.use(Tag)
  app.use(Table)
  app.use(Tooltip)
  app.use(Tree)
  app.use(Tabs)
  app.use(Timeline)
  app.use(Transfer)
  app.use(Typography)
  app.use(TimePicker)
  app.use(TreeSelect)
  app.use(Upload)
}
